# TODO This hard coded archetype version need to be fixed, or removed from here some how
archetype:
  name: brzy-webapp-archetype
  org: org.brzy.webapp
  version: 1.0.0.beta4 # todo this needs to be set on the build

build:
  default_task: "package"
  compiler_type: "scala"
  compiler_version: "2.10.0"
  compiler_args: ""
  target_dir: "{working_dir}/target"
  webapp_dir: "{working_dir}/webapp"
  package_classifier: ""
  package_source: false
  package_doc: false
  deploy_target: ""
  publish_target: ""
  version_control: ""
  fab_cache_dir: "{user.home}/.fab"
  fab_home_dir: "{env.FAB_HOME}"
  builder_dir: "{working_dir}/.fab"
  builder_cache_dir: "{builder_dir}/fab"
  builder_code_dir: "{builder_dir}/fab_code"
  builder_lib_dir: "{builder_dir}/fab_lib"
  source_dir: "{woking_dir}/src/scala"
  resource_dir: "{woking_dir}/src/resources"
  classes_dir: "{target_dir}/classes"
  test_source_dir: "{working_dir}/test/scala"
  test_resource_dir: "{working_dir}/test/resources"
  test_classes_dir: "{target_dir}/test-classes"

views:
  name: brzy-scalate
  org: org.brzy
  version: "${brzy-scalate-version}"

repositories:
  - {id: brzy, url: "http://repo.brzy.org/content/repositories/releases"}
  - {id: maven-ctl, url: "http://repo.maven.apache.org/maven2"}

dependencies:
  - {conf: provided, org: org.scala-lang, name: scala-compiler, rev: "${scala.version}", transitive: false}
  - {conf: provided, org: org.scala-lang, name: scala-library, rev: "${scala.version}", transitive: false}
  - {conf: provided, conf: org.apache.tomcat, name: tomcat-servlet-api, rev: 7.0.35, transitive: false}
  - {conf: compile, org: org.brzy.webapp, name: brzy-webapp, rev: "${project.version}", transitive: false}
  - {conf: compile, org: org.brzy.fab, name: fab-configuration, rev: "${fab-configuration-version}", transitive: false}
  - {conf: compile, org: org.brzy.beanwrap, name: beanwrap, rev: "${beanwrap-version}"}
  - {conf: compile, org: com.google.guava, name: guava, rev: "r06", transitive: false}
  - {conf: compile, org: org.yaml, name: snakeyaml, rev: "1.7"}
  - {conf: compile, org: commons-lang, name: commons-lang, rev: "2.5"}
  - {conf: compile, org: ch.qos.logback, name: logback-classic, rev: "1.0.9", transitive: false}
  - {conf: compile, org: ch.qos.logback, name: logback-core, rev: "1.0.9", transitive: false}
  - {conf: compile, org: org.slf4j, name: slf4j-api, rev: "1.7.2",transitive: false}

web_xml:
  - listener: {listener-class: org.brzy.application.WebAppListener}
  - filter: {filter-name: BrzyFilter, filter-class: org.brzy.webapp.BrzyFilter}
  - filter-mapping: {filter-name: BrzyFilter, url-pattern: "/*"}
  - servlet: { servlet-name: BrzyServlet, servlet-class: org.brzy.webapp.BrzyServlet, load-on-startup: "1"}
  - servlet-mapping: { servlet-name: BrzyServlet, url-pattern: "*.brzy"}
  - welcome-file-list: { welcome-file: "index.brzy"}
  - error-page: { error-code: "404", location: "/errors/404.ssp"}
  - error-page: { error-code: "500", location: "/errors/500.ssp"}
  - error-page: {exception-type: java.lang.Throwable, location: "/errors/500.ssp"}

