

project:
  scala_version: ${scala.version}
  package_type: war
  module_resources: ".brzy/modules"
  cache: ".brzy"
  package_source: false
  package_doc: false

views:
  name: brzy-scalate
  org: org.brzy.mod
  version: "${brzy-scalate-version}"

repositories:
  - {id: brzy, url: http://repo.brzy.org/content/repositories/releases}
  - {id: brzy-snapshot, url: http://repo.brzy.org/content/repositories/snapshots}
  - {id: scala-tools, url: http://scala-tools.org/repo-releases}
  - {id: maven-central, url: http://repo1.maven.org/maven2}
  - {id: reflections-repo, url: http://reflections.googlecode.com/svn/repo}
  - {id: jboss, url: http://repository.jboss.com/maven2}
  - {id: java-net2, url: http://download.java.net/maven/2}

dependencies:
  - {conf: provided, org: org.scala-lang, name: scala-compiler, rev: "${scala.version}", transitive: false}
  - {conf: provided, org: org.scala-lang, name: scala-library, rev: "${scala.version}", transitive: false}
  - {conf: compile, org: org.brzy, name: brzy-webapp, rev: "${brzy-webapp-version}", transitive: false}
  - {conf: compile, org: org.brzy.fab, name: fab-conf, rev: "${fab-conf-version}", transitive: false}
  - {conf: compile, org: javassist, name: javassist, rev: "3.11.0.GA", transitive: false}
  - {conf: compile, org: org.aspectj, name: aspectjweaver, rev: "1.6.8", transitive: false}
  - {conf: compile, org: org.reflections, name: reflections, rev: "0.9.5-RC2", transitive: false}
  - {conf: compile, org: dom4j, name: dom4j, rev: "1.6.1", transitive: false}
  - {conf: compile, org: com.google.guava, name: guava, rev: "r06", transitive: false}
  - {conf: compile, org: org.jyaml, name: jyaml, rev: "1.3"}
  - {conf: compile, org: commons-lang, name: commons-lang, rev: "2.5"}
  - {conf: compile, org: ch.qos.logback, name: logback-classic, rev: "0.9.24",transitive: false}
  - {conf: compile, org: ch.qos.logback, name: logback-core, rev: "0.9.24",transitive: false}
  - {conf: compile, org: org.slf4j, name: slf4j-api, rev: "1.6.1",transitive: false}
  - {conf: test, org: junit, name: junit, rev: "4.8.1"}
  - {conf: test, org: org.scalatest, name: scalatest, rev: "1.2", transitive: false}
  
web_xml:
  - context-param: { param-name : brzy-env, param-value: development}
  - listener: {listener-class: org.brzy.application.WebAppListener}
  - filter: {filter-name: BrzyFilter, filter-class: org.brzy.webapp.action.BrzyFilter}
  - filter-mapping: {filter-name: BrzyFilter, url-pattern: "/*"}
  - servlet: { servlet-name: BrzyServlet, servlet-class: org.brzy.webapp.action.BrzyServlet, load-on-startup: "1"}
  - servlet-mapping: { servlet-name: BrzyServlet, url-pattern: "*.brzy"}
  - welcome-file-list: { welcome-file: "index.brzy"}

